### ISSUE TITLE
outputs not always showing up in next op

### ISSUE THREAD

**Issue by zachpuck** [opspec-io/spec#103]
when chaining ops together and using multiple outputs if the previous op ends to quickly the outputs do not always get picked up by the next op. 

example of workaround:

`sleep 5
echo "output1=foo"
sleep 5`

**Comment by chrisdostert** [comment]
@zachpuck moved to [opctl/issues/174](https://github.com/opctl/opctl/issues/174) as issue w/ opctl, not spec
