### ISSUE TITLE
Interpolation escape syntax

### ISSUE THREAD

**Issue by chrisdostert** [opspec-io/spec#193]
## Background
In order to un ambiguously interpolate expressions we need an escape character.

### Shell
`\` blindly treated as escape 
code
```sh
echo "\\ \$hello" 
```
result
`\ $hello`

### Javascript
`\` blindly treated as escape 
code
```javascript
console.log(`\\ \${hello}`)
```

result
`\ ${hello}`

### Docker compose
`$` immediately preceeding `$` treated as escape 
code
```yaml
$$ $${hello}
```

result
`$ ${hello}`

### Golang
`%` blindly treated as escape 
code
```golang
package main

import "fmt"

func main() {
	fmt.Printf("%% %%v")
}
```

result
```
% %v
```

### Proposal 1
`\` preceeding accessor `$()` treated as escape (or escape of escape, and so on...)
code
```yaml
\\ \$(hello)
```

result
```yaml
\\ $(hello)
```
### Proposal 2
`\` blindly treated as escape
code
```yaml
\\ \$(hello)
```

result
```yaml
\ $(hello)
```

### Proposal 3
`$` preceeding accessor `$()` treated as escape (or escape of escape, and so on...)
code
```yaml
$$ $$(hello)
```

result
```yaml
$$ $(hello)
```

**Comment by psamaan** [comment]
I like proposal 1 because I can't think of a situation where it would be an improvement over 1
I also don't like 3 because visually I don't get how the symbol for interpolation can double as escape

**Comment by psamaan** [comment]
I meant can't think of a situation where 2 would be an improvement over 1, functionally

**Comment by sai-li** [comment]
Happy with either 1 or 2

**Comment by petedv** [comment]
Is the proposal 3 example correct? Shouldnt the output be `$ $(hello)`?
I think proposal 2 adds more flexibility for future uses. Should you add any other syntax that also requires escaping. 

We should also consider the reverse where you want to have text that looks like the escaped syntax. How would you represent the resulting text `\$` in proposal 1?

**Comment by chrisdostert** [comment]
@psamaan , @sai-li , @petedv, thanks for response.

@petedv yes example 3 output is as intended but the description wasn't; I took another stab at it. 

I'm hesitant to deviate from "the norm" (proposal 2) too but i'm worried about requiring duplication of every `\` inside fields supporting interpolation. It seems like a lame user experience. I think if we have more needs pop up we theoretically could use proposal 1 for them too, but hard to predict w/out knowing the uses ahead of time. 

i'm not sure if it's what you mean but in all the proposals, it's assumed you add another escape character to "escape the escape" (and another to escape the escape of the escape.. etc)

**Comment by chrisdostert** [comment]
@zachpuck I have no idea what you're saying lol

**Comment by chrisdostert** [comment]
@zachpuck Guess you're comparing to like output of json escaping, html escaping etc.. I get your point now I think but i'm not sure how it helps us

**Comment by zachpuck** [comment]
i guess i am just saying my first response is to go with proposal 2 but proposal 1 works as well. Shelly voted for proposal 1.

**Comment by SudhindraKovalam** [comment]
I vote for proposal 1
parity with javascript

**Comment by chrisdostert** [comment]
proposal 2 is what javascript does. I'm not sure why javascript is unintelligent about it.. because it's easier to parse? I'd love to know

**Comment by habibbhutto** [comment]
I think 2 is better, I am okay if we go with 1

**Comment by habibbhutto** [comment]
After discussing with @chrisdostert I think option 1 is better, which is improvement on 2.

**Comment by chrisdostert** [comment]
Thanks all for your input and for helping arrive at a great solution. For those who may have missed it, Opspec 0.1.6 has been released w/ support for proposal 1, i.e. `\$(not-a-ref)`
