### ISSUE TITLE
Add support for private images

### ISSUE THREAD

**Issue by chrisdostert** [opspec-io/spec#71]
Userstory:
As a spec author
I would like the ability to specify pullSecret & pullIdentity
In order to use images from private repositories

Example:
```yaml
# pullSecret & pullIdentity are interpolated strings
image: { ref: docker: 1.13, pullSecret: xxx, pullIdentity: xyz }
```

**Comment by chrisdostert** [comment]
@zachpuck @psamaan

**Comment by psamaan** [comment]
Looks all right

**Comment by zachpuck** [comment]
look good to me
